### ISSUE TITLE
Na pagina de status do pedido, quando selecionado pix, o horário de retirada apresentado é incorreto

### ISSUE THREAD

**Issue by FernandaFBMarques** [theomilll/CLEO#14]
Na página status do pedido, quando selecionado pix, o horário de retirada apresentado é diferente do qual o usuário inseriu. Consertar para o retorno correto de acordo com o que o usuário selecionar.
<img width="1440" alt="Captura de Tela 2023-05-15 às 20 06 09" src="https://github.com/theomilll/CLEO/assets/101741395/7912fda9-e34f-4b74-8109-f49f2f2f68c6">
<img width="1440" alt="Captura de Tela 2023-05-15 às 20 06 16" src="https://github.com/theomilll/CLEO/assets/101741395/d1f66b15-d503-4354-8f5a-cdf1913cc501">

**Comment by Criismnaga** [comment]
Resolvido
