### ISSUE TITLE
Botão adicionar da pagina product_detail

### ISSUE THREAD

**Issue by hhenrique7510** [theomilll/CLEO#2]
Quando adicionado o item por essa pagina ele  adiciona 1 a mais ao carrinho.

**Comment by FernandaFBMarques** [comment]
<img width="1440" alt="Captura de Tela 2023-05-14 às 21 19 45" src="https://github.com/theomilll/CLEO/assets/101741395/dc196bd8-a1ef-4535-9b22-88619252a908">
<img width="1440" alt="Captura de Tela 2023-05-14 às 21 21 10" src="https://github.com/theomilll/CLEO/assets/101741395/f68c6789-a39d-4359-b6df-71aa49e1b896">

**Comment by theomilll** [comment]
Resolvido 🫡

**Comment by FernandaFBMarques** [comment]
🙏

Em dom., 14 de mai. de 2023 às 21:25, TheoMoura ***@***.***>
escreveu:
